resolver: lts-3.19
packages:
- '.'
extra-deps:
- GLURaw-1.5.0.2
- GLUT-2.7.0.3
- ObjectName-1.1.0.0
- OpenGL-2.12.0.1
- OpenGLRaw-2.5.5.0
- bit-array-0.1.0.1
- gloss-1.9.4.1
- gloss-rendering-1.9.3.1
- numeric-qq-0.1.3
flags: {}
extra-package-dbs: []
