resolver: lts-3.20
packages:
- '.'
- location:
    git: https://github.com/ekmett/ersatz.git
    commit: 5b287fedf41b7f76559ea8b68f14f108fa076f19
  extra-dep: true
extra-deps:
- GLURaw-1.5.0.2
- GLUT-2.7.0.3
- ObjectName-1.1.0.0
- OpenGL-2.12.0.1
- OpenGLRaw-2.5.5.0
- gloss-1.9.4.1
- gloss-rendering-1.9.3.1
flags: {}
extra-package-dbs: []
